create toggle component
LCarrasquel14/ToDo pull request #1
Opened 2024-07-08 14:48 UTC by LCarrasquel14

add history for toggle

2024-07-08 22:08 UTC, LCarrasquel14 commented
add an onclick to change state and add the styles to the toggle

2024-07-09 18:06 UTC, enmaGit commented on src/Components/bar.tsx
> +  const percentage = Math.round((progress / maxLimit) * 100);
```suggestion
  const percentage = Math.round((progress / maxLimit) * 100);
  const barPercentage = `${percentage}%`
```

2024-07-09 18:22 UTC, enmaGit requested changes

2024-07-09 18:22 UTC, enmaGit commented on src/app/layout.tsx
> +        <script
Let's use npm instead of this, there should be a way to do it with npm instead of a cdn

2024-07-09 18:22 UTC, enmaGit commented on src/ui/Menu/Menu.tsx
>                <ol onClick={() => onOptionClicked(option.key)} key={option.key}>
why did you use `ol` instead of `li`?

2024-07-09 18:22 UTC, enmaGit commented on src/ui/Modal/Modal.tsx
> +        <Icon icon="close" size={24} />
Why to place the Icon inside of a `i` tag? The Icon should be able to receive classes like:
`<Icon icon="close" size={24}  className="cursor-pointer" />`

2024-07-09 18:22 UTC, enmaGit commented on src/ui/Progress/Progress.tsx
> +            <Icon icon="tasks" size={16} />
Same here:
`<Icon icon="tasks" size={16} className="cursor-pointer mt-[7px]" onClick={() => setShowMenu(!showMenu)} />`

2024-07-09 18:22 UTC, enmaGit commented on src/ui/Toggle/Toggle.tsx
> +  const [selected, setSelected] = useState(buttons[0].selected);
why do you need this state? Is not being used in the component?

2024-07-09 18:22 UTC, enmaGit commented on src/ui/Toggle/Toggle.tsx
> +    buttons.map((button) => {
You shouldn't change the props you receive. You are changing buttons and that's not a safe pattern

2024-07-09 18:22 UTC, enmaGit commented on src/ui/Toggle/Toggle.tsx
> +        setSelected(false);
you are changing this state to force a rerender but that's not a safe operation because your component doesn't rely on selected but on buttons. So you should create a state based on the the props

2024-07-09 18:22 UTC, enmaGit commented on src/ui/Toggle/Toggle.tsx
> +  const [selected, setSelected] = useState(buttons[0].selected);
```suggestion
  const [selected, setSelected] = useState([{...buttons[0], selected: false}, {...buttons[1], selected: false}]);
```

2024-07-09 18:32 UTC, LCarrasquel14 commented on src/ui/Menu/Menu.tsx
>                <ol onClick={() => onOptionClicked(option.key)} key={option.key}>
I wanted to place the side line but then I remembered that tailwind resets all the styles

2024-07-09 18:44 UTC, LCarrasquel14 commented on src/app/layout.tsx
> +        <script
In order to use what you sent me, I have to run it through CDN, that's what the documentation says.
![Captura de pantalla 2024-07-09 144149](https://github.com/LCarrasquel14/ToDo/assets/118396377/b811bf39-8eb7-4014-920a-4b3e1823e800)

2024-07-09 19:36 UTC, LCarrasquel14 commented on src/ui/Modal/Modal.tsx
> +        <Icon icon="close" size={24} />
Do I remove the icon component from the i tag? Or do I just add the classname to the icon because if I remove the component I would have to handle the clicks on the icon component just like the other classes.

2024-07-09 19:42 UTC, LCarrasquel14 commented on src/ui/Toggle/Toggle.tsx
> +  const [selected, setSelected] = useState(buttons[0].selected);
so that the component can be re-rendered and thus be able to make the animation of changing location

2024-07-09 19:53 UTC, LCarrasquel14 commented on src/app/layout.tsx
> +        <script
![image](https://github.com/LCarrasquel14/ToDo/assets/118396377/8ac12896-b6ef-466b-a690-80f8f96cf9b8)
thi's my code

2024-07-09 19:54 UTC, LCarrasquel14 commented on src/ui/Menu/Menu.tsx
>                <ol onClick={() => onOptionClicked(option.key)} key={option.key}>
but I already corrected it

2024-07-19 21:56 UTC, enmaGit requested changes

2024-07-19 21:56 UTC, enmaGit commented on src/Components/bar.tsx
> +const percentageBar = ({ progress, maxLimit, validate }: Props) => {
`validate` should be calculated inside  the component

2024-07-19 21:56 UTC, enmaGit commented on src/ui/Progress/Progress.tsx
> +        validate={validate}
validate={validate} This shouldn't be sent here. It should be handle internally in the component

2024-07-19 22:23 UTC, enma21498 approved these changes

2024-07-19 22:40 UTC, LCarrasquel14 commented
finish component toggle

2024-07-23 15:01 UTC, LCarrasquel14 commented
conflicts resolved

2024-07-23 15:01 UTC, merged