Feature/tag
LCarrasquel14/ToDo pull request #2
Opened 2024-07-09 18:51 UTC by LCarrasquel14

added styles I need to place the line below and when clicking it calls handleBoardView and makes a console log showing the id that we passed through prot

2024-07-11 15:21 UTC, enmaGit approved these changes

2024-07-11 15:21 UTC, enmaGit commented on src/Components/bar.tsx
> +const percentageBar = ({ progress, maxLimit, validate }: Props) => {
Name of the components should start with capital case

2024-07-11 15:21 UTC, enmaGit commented on src/app/layout.tsx
> +          src="https://cdnjs.cloudflare.com/ajax/libs/react-modal/3.14.3/react-modal.min.js"
We need to remove this react-modal script. This needs to be installed by npm not by the cdn

2024-07-11 15:21 UTC, enmaGit commented on src/ui/Modal/Modal.tsx
> +        <i
Why is this open separated from the modal?

2024-07-11 15:21 UTC, enmaGit commented on src/ui/Tag/Tag.tsx
> +const Tag = ({ tagContainer }: TagProps) => {
It is not Tag but Tab

2024-07-11 15:21 UTC, enmaGit commented on src/ui/Toggle/Toggle.tsx
> +        button.selected = false;
You are mutating the props and this is not safe. You shouldn't mutate the props, you should change the state and then comunicate to the parent through a callback that the input changed.

2024-07-11 16:08 UTC, enmaGit requested changes

2024-07-11 16:08 UTC, enmaGit commented on src/ui/Toggle/Toggle.tsx
> +const Toggle = ({ buttons }: Props) => {
```suggestion
const Toggle = ({ buttons, onToggle }: Props) => {
```

2024-07-11 16:08 UTC, enmaGit commented on src/ui/Toggle/Toggle.tsx
> +    buttons.map((button) => {
```suggestion
    buttons.forEach((button) => {
        setSelected(selected === 1 ? 0 : 1);
        onToggle();
    }
```

2024-07-11 16:08 UTC, enmaGit commented on src/ui/Modal/Modal.tsx
> +        {children}
```suggestion
    <>
         <i></i>
           {children}
     </>
```

2024-07-16 21:10 UTC, enmaGit requested changes

2024-07-16 21:10 UTC, enmaGit commented on src/Components/bar.tsx
> +const PercentageBar = ({ progress, maxLimit, validate }: Props) => {
We need to remove the validte from here, any validation logic for this should be inside the component

2024-07-16 21:10 UTC, enmaGit commented on src/ui/Progress/Progress.tsx
> +  const validate = progress <= maxLimit;
This logic needs to be inside the ProgressBar

2024-07-17 16:18 UTC, LCarrasquel14 commented
squash and merge

2024-07-17 17:02 UTC, merged