Feature/sidebar
LCarrasquel14/ToDo pull request #3
Opened 2024-07-24 17:15 UTC by LCarrasquel14

Input sidebar and loading button components created and styles added

2024-07-26 14:36 UTC, enmaGit requested changes

2024-07-26 14:36 UTC, enmaGit commented on src/Components/Form.tsx
> +const htmlForm: React.FC = () => {
As this seems to be a specific form, not a generic one, the name should reflect its purpose. So, CreateProjectForm or something like that.

2024-07-26 14:36 UTC, enmaGit commented on src/ui/LoadableButton/LoadableButton.tsx
> +const LoadableButton = ({ isLoading }: Props) => {
This should receive the same Props as the button Props, and the isLoading prop

2024-07-26 14:36 UTC, enmaGit commented on src/ui/LoadableButton/LoadableButton.tsx
> +      label={!isLoading ? "Loading..." : "LoadableButton"}
So, it will show Loadbalebutton as a label when it's not loading and that's not expected

2024-07-26 14:36 UTC, enmaGit commented on src/ui/Modal/Modal.tsx
> +      <div onClick={openModal}>{children}</div>
This shouldn't be here, we won't open the modal from the modal.

2024-07-26 14:36 UTC, enmaGit commented on src/ui/SideBar/SideBar.tsx
> +        <ModalComponent isOpen={false}>
this is related to the other issue above, So here should be the button you will click to open the modal, and the state to know if the modal is open or not should be here.

2024-07-26 15:30 UTC, enmaGit requested changes

2024-07-26 15:30 UTC, enmaGit commented on src/Components/CreateProjectForm.tsx
> +const AddModalForm: React.FC = () => {
the name is incorrect, it should be CreateProjectForm

2024-07-26 15:30 UTC, enmaGit commented on src/Components/Modal.tsx
> +  function openModal() {
this function is not used, so it should be removed

2024-07-26 15:30 UTC, enmaGit commented on src/ui/LoadableButton/LoadableButton.tsx
> +type Props = {
the definition should be:
type Props = ButtonProps | {
   isLoading: string
}

2024-07-26 17:07 UTC, LCarrasquel14 commented
add the ListModal, ProjectModal and the taskModal

2024-07-26 19:39 UTC, enmaGit approved these changes

2024-08-01 15:58 UTC, enmaGit requested changes

2024-08-01 15:58 UTC, enmaGit commented on src/ui/AddListModal/AddListModal.tsx
> +  const onINputChange = (value: string) => {
you have a typo here, onInput you put N in uppercase

2024-08-01 15:58 UTC, enmaGit commented on src/ui/AddListModal/AddListModal.tsx
> +    console.log(inputValue);
remove this log if not being used, please

2024-08-01 15:58 UTC, enmaGit commented on src/ui/AddTaskModal/AddTaskModal.tsx
> +const AddTaskModal = ({ isOpen }: Props) => {
this should have a callback onAddTask: (taskInfo: Task) that should be called when save is hit

2024-08-01 15:58 UTC, enmaGit commented on src/ui/AddProjectModal/AddProjectModal.tsx
> +const AddProjectModal = ({ isOpen }: Props) => {
this should have a callback onAddProject: (projectInfo: Project) that should be called when save is hit

2024-08-01 15:58 UTC, enmaGit commented on src/ui/AddListModal/AddListModal.tsx
> +const AddListModal = ({ isOpen }: Props) => {
this should have a callback onAddList: (listInfo: List) that should be called when save is hit

2024-08-06 16:04 UTC, enmaGit requested changes

2024-08-06 16:04 UTC, enmaGit commented on src/Components/CreateProjectForm.tsx
> +    setOnwerId("");
We can change this later, but I think the owner should not be assigned by the user but by the system. So the current user should be the owner of the project.

2024-08-06 16:04 UTC, enmaGit commented on src/ui/AddTaskModal/AddTaskModal.tsx
> +  const options = [
The lists should be received by props.

2024-08-06 16:04 UTC, enmaGit commented on src/ui/Input/Input.tsx
> +        required
The required value should come by props, as not always an input is required.

2024-08-14 20:43 UTC, enmaGit approved these changes

2024-08-14 22:40 UTC, merged